version: "3.9"

services:
  globetrotter:
    build: .
    container_name: globetrotter_app
    ports:
      - "5000:5000"
    # Mount local code so changes are reflected without rebuilding the image
    volumes:
      - .:/globetrotter
    environment:
      - PORT=5000
